server:
  port: 8181
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    min-spare-threads: 30

spring:
  application:
    name: ${project.artifactId}
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      validation-query-timeout: -1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      share-prepared-statements: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hdw_dubbo?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3600ms
    #    cluster:
    #      max-redirects: 3
    #      nodes: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004,127.0.0.1:7005
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
        max-wait: 6000ms
      shutdown-timeout: 100ms
  boot:
    admin:
      client:
        url: http://127.0.0.1:8180
        instance:
          service-base-url: http://127.0.0.1:${server.port}
          management-base-url: http://127.0.0.1:${server.port}

mybatis-plus:
  mapper-locations: classpath*:com/hdw/*/mapper/sqlMapperXml/*Mapper.xml
  type-aliases-package: com.hdw.*.entity
  global-config:
    db-config:
      id-type: id_worker
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

dubbo:
  scan:
    base-packages: com.hdw.*.service
  application:
    id: hdw-base-provider
    name: ${dubbo.application.id}
    qos:
      enable: false
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    threadpool: fixed
    threads: 200
    payload: 52428800
  registry:
    id: hdw-registry
    address: zookeeper://127.0.0.1:2181
    file: /output/cache/hdw-base-provider.cache
    timeout: 5000
    session: 60000
    check: true
  provider:
    id: ${dubbo.application.id}
    protocol: ${dubbo.protocol.name}
    group: hdw-base
    version: 1.0.0
    timeout: 60000
    loadbalance: roundrobin
    weight: 5
    retries: 2
    actives: 200
    executes: 200

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    dubbo:
      enable: true
      dubbo-shutdown.enabled: true
      dubbo-configs.enabled: true
      dubbo-services.enabled: true
      dubbo-references.enabled: true
      dubbo-properties.enabled: true
  health:
    dubbo:
      status:
        defaults: memory,load
        extras: registry,load,threadpool

info:
  name: 基础平台SERVICE服务
  version: ${project.version}

hdw:
  expire: 1800